#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the moiro_agv usb connection."
echo ""

sudo cp `sudo cp `ros2 pkg prefix moiro_agv_bringup`/share/moiro_agv_bringup/script/99-moiro_agv-cdc.rules /etc/udev/rules.d/

echo ""
echo "Reload rules"
echo ""
sudo udevadm control --reload-rules
sudo udevadm trigger
